[package]
name = "langtool"
version = "0.1.0"
authors = ["Henrik Rydg√•rd <hrydgard@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
